version: "3.9"

services:
  nginx:
    image: jinjohn/sak-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:80
    networks:
      - saksiam-django-class

  django:
    image: jinjohn/sak-django
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - saksiam-django-class
    command: /start

networks:
  saksiam-django-class:
    external: true