version: "3.9"

services:
  nginx:
    container_name: nginx
    image: jinjohn/sak-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:80
    networks:
      - saksiam-django-class

  django:
    container_name: django
    image: jinjohn/sak-django
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - saksiam-django-class
    command: /start

  postgres_sak_db:
    container_name: postgres_sak_db
    image: jinjohn/postgres     
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - saksiam-django-class

volumes:
    postgres-data:

networks:
  saksiam-django-class: